// Copyright 2026 Azahar Emulator Project
// Licensed under GPLv2 or any later version

#pragma once

#include <array>
#include <functional>
#include <memory>
#include <span>
#include <vector>

#include "common/common_types.h"

namespace Service::NWM::UdsReal {

struct CapturedBeacon {
    std::vector<u8> frame;
    std::array<u8, 6> transmitter_address{};
    std::array<u8, 6> destination_address{};
    u8 channel{};
    u32 wlan_comm_id{};
    u8 id{};
};

// A non-beacon 802.11 MPDU captured from the physical radio. The addresses are normalized to
// logical transmitter/destination/BSSID values even when ToDS or FromDS changes their on-air
// header positions. body excludes the 24-byte 802.11 header and any trailing FCS.
struct CapturedFrame {
    // Complete captured 802.11 MPDU, excluding radiotap and any trailing FCS. Keeping this next
    // to the normalized fields lets connection-handshake diagnostics verify the exact bytes that
    // arrived instead of reconstructing them from parsed state.
    std::vector<u8> mpdu;
    std::vector<u8> body;
    std::array<u8, 6> transmitter_address{};
    std::array<u8, 6> destination_address{};
    std::array<u8, 6> bssid{};
    u16 frame_control{};
    u16 sequence_control{};
    u8 channel{};
    u8 type{};
    u8 subtype{};
};

class Nl80211Monitor {
public:
    using BeaconCallback = std::function<void(CapturedBeacon)>;
    using FrameCallback = std::function<void(CapturedFrame)>;

    Nl80211Monitor();
    ~Nl80211Monitor();

    Nl80211Monitor(const Nl80211Monitor&) = delete;
    Nl80211Monitor& operator=(const Nl80211Monitor&) = delete;

    // Starts a physical monitor asynchronously. The requested channel is tried
    // first, then the monitor scans the primary Nintendo channels 1, 6, and 11
    // until it finds a Nintendo beacon. A detected channel remains selected
    // while those beacons continue arriving, with a long idle timeout for
    // bursty discovery traffic.
    void Start(u16 channel, const std::array<u8, 6>& local_address,
               BeaconCallback beacon_callback, FrameCallback frame_callback);

    // Supplies the latest UDS beacon body generated by nwm::UDS. The monitor worker wraps it in
    // radiotap and 802.11 management headers, adjusts the DS channel to the radio's actual current
    // channel, and broadcasts it through the monitor interface at the normal beacon interval.
    void SubmitBeacon(std::span<const u8> beacon_body,
                      const std::array<u8, 6>& host_address);

    // Queues a complete 802.11 MPDU (without radiotap or FCS) for monitor-mode injection.
    void SubmitFrame(std::span<const u8> frame);

    // Tunes and temporarily locks discovery to the channel advertised by the UDS network which
    // the game selected. The request is retained while the worker is still starting.
    void SelectPeerChannel(u16 channel);

    // Legacy experimental AP-data entry point. The isolated ACK-shell test deliberately leaves
    // this unused: software CCMP and monitor injection remain the only data path.
    void SubmitAccessPointData(std::span<const u8> payload,
                               const std::array<u8, 6>& transmitter_address,
                               const std::array<u8, 6>& destination_address);

    // Prepares a companion nl80211 AP interface for the currently hosted UDS network. It exists
    // only to give the firmware the host BSSID and a station table for timing-critical 802.11
    // acknowledgements. It never owns CCMP keys or application data.
    void ConfigureAccessPoint(const std::array<u8, 6>& host_address,
                              const std::array<u8, 16>& ccmp_key, u32 network_id,
                              u8 max_stations);

    // Requests that the prepared AP be started on the monitor's current channel. This is queued
    // when a retail station begins open-system authentication, so slow nl80211 work never blocks
    // the emulator's service thread.
    void ActivateAccessPoint();

    // Queues a retail association request for unkeyed, unauthorized registration in the kernel
    // AP station table. association_body begins with capability/listen-interval followed by IEs.
    void RegisterAccessPointStation(const std::array<u8, 6>& station_address,
                                    std::span<const u8> association_body);

    // Removes a departing retail station from the kernel table, if it was registered.
    void RemoveAccessPointStation(const std::array<u8, 6>& station_address);

    // Client-role counterpart of the ACK shell. When Azahar joins a retail-hosted network, the
    // retail host's unicast frames to us (authentication/association responses, EAPoL-Logoff,
    // keepalive replies) need immediate hardware ACKs or the host gives up on the join. This
    // prepares the same companion AP interface, but with OUR address, brings it up with a
    // minimal non-Nintendo hidden beacon (never advertised as a UDS network), and registers the
    // retail host as a station so the firmware acknowledges its frames. association_body is the
    // body of our own association request (capability, listen interval, SSID, rates).
    void ConfigureClientAckShell(const std::array<u8, 6>& own_address,
                                 const std::array<u8, 6>& host_address, u32 network_id,
                                 std::span<const u8> association_body);

    // Stops the AP portion while leaving physical discovery running.
    void ResetAccessPoint();

    void Stop();
    [[nodiscard]] bool IsRunning() const;

private:
    struct Impl;
    std::unique_ptr<Impl> impl;
};

} // namespace Service::NWM::UdsReal
