// Copyright 2026 Azahar Emulator Project
// Licensed under GPLv2 or any later version

#pragma once

#include <array>
#include <functional>
#include <memory>
#include <span>
#include <vector>

#include "common/common_types.h"

namespace Service::NWM::UdsReal {

struct CapturedBeacon {
    std::vector<u8> frame;
    std::array<u8, 6> transmitter_address{};
    std::array<u8, 6> destination_address{};
    u8 channel{};
    u32 wlan_comm_id{};
    u8 id{};
};

// A non-beacon 802.11 MPDU captured from the physical radio. The addresses are normalized to
// logical transmitter/destination/BSSID values even when ToDS or FromDS changes their on-air
// header positions. body excludes the 24-byte 802.11 header and any trailing FCS.
struct CapturedFrame {
    std::vector<u8> body;
    std::array<u8, 6> transmitter_address{};
    std::array<u8, 6> destination_address{};
    std::array<u8, 6> bssid{};
    u16 frame_control{};
    u16 sequence_control{};
    u8 channel{};
    u8 type{};
    u8 subtype{};
};

class Nl80211Monitor {
public:
    using BeaconCallback = std::function<void(CapturedBeacon)>;
    using FrameCallback = std::function<void(CapturedFrame)>;

    Nl80211Monitor();
    ~Nl80211Monitor();

    Nl80211Monitor(const Nl80211Monitor&) = delete;
    Nl80211Monitor& operator=(const Nl80211Monitor&) = delete;

    // Starts a physical monitor asynchronously. The requested channel is tried
    // first, then the monitor scans the primary Nintendo channels 1, 6, and 11
    // until it finds a Nintendo beacon. A detected channel remains selected
    // while those beacons continue arriving, with a long idle timeout for
    // bursty discovery traffic.
    void Start(u16 channel, BeaconCallback beacon_callback, FrameCallback frame_callback);

    // Supplies the latest UDS beacon body generated by nwm::UDS. The monitor worker wraps it in
    // radiotap and 802.11 management headers, adjusts the DS channel to the radio's actual current
    // channel, and broadcasts it through the monitor interface at the normal beacon interval.
    void SubmitBeacon(std::span<const u8> beacon_body,
                      const std::array<u8, 6>& host_address);

    // Queues a complete 802.11 MPDU (without radiotap or FCS) for monitor-mode injection.
    void SubmitFrame(std::span<const u8> frame);

    void Stop();
    [[nodiscard]] bool IsRunning() const;

private:
    struct Impl;
    std::unique_ptr<Impl> impl;
};

} // namespace Service::NWM::UdsReal
